import { rand } from './core';

export function bird() {
  return rand([
    'Red-necked Phalarope',
    'Cliff Swallow',
    'Loggerhead Kingbird',
    'Aztec Thrush',
    'Hooded Warbler',
    'Common Pochard',
    "Scott's Oriole",
    'Black-browed Albatross',
    'Monk Parakeet',
    'Magnificent Hummingbird',
    'Broad-billed Sandpiper',
    'Bushtit',
    'Mexican Jay',
    'Hooded Merganser',
    'Wood Stork',
    "Ross's Gull",
    'Green Sandpiper',
    'Whooping Crane',
    'Pygmy Nuthatch',
    'Lesser Nighthawk',
    'Narcissus Flycatcher',
    'Long-eared Owl',
    'Bay-breasted Warbler',
    'Gull-billed Tern',
    'Bumblebee Hummingbird',
    'Northern Goshawk',
    'Sooty Tern',
    'Altamira Oriole',
    'Ring-necked Duck',
    'Whooper Swan',
    'Western Sandpiper',
    'Osprey',
    'Red-billed Tropicbird',
    'Mountain Bluebird',
    'Wood Sandpiper',
    'Tropical Kingbird',
    "Bullock's Oriole",
    "Baird's Sparrow",
    'Dusky-capped Flycatcher',
    'Mourning Dove',
    'Marbled Murrelet',
    'Yellow-billed Loon',
    'Northern Pintail',
    'Inca Dove',
    'Blue-winged Teal',
    'Least Sandpiper',
    'Lesser Scaup',
    "Brandt's Cormorant",
    "Cassin's Kingbird",
    'Southern Martin',
    'King Eider',
    'Spot-billed Duck',
    'Short-tailed Hawk',
    'Ruddy Turnstone',
    'Black-capped Vireo',
    'Lesser Frigatebird',
    'Whiskered Auklet',
    'Great Frigatebird',
    'Common Black-Hawk',
    'Purple Gallinule',
    'Paint-billed Crake',
    'Song Sparrow',
    'Jungle Nightjar',
    'Eastern Meadowlark',
    'Eurasian Dotterel',
    'Snowy Egret',
    'Brambling',
    'Passenger Pigeon',
    "Ross's Goose",
    'Plumbeous Vireo',
    "Audubon's Oriole",
    'Dusky Warbler',
    'Piping Plover',
    'White-winged Tern',
    'Chestnut-collared Longspur',
    'Hooded Oriole',
    'Black Phoebe',
    'White-tailed Tropicbird',
    'Great Horned Owl',
    'Tufted Titmouse',
    'Snowy Owl',
    'Calliope Hummingbird',
    'Northern Beardless-Tyrannulet',
    'Brown Shrike',
    'Mew Gull',
    'Cape May Warbler',
    'Lark Bunting',
    'Black-tailed Gnatcatcher',
    'Common Yellowthroat',
    'White-winged Dove',
    'Oriental Greenfinch',
    'Roseate Spoonbill',
  ]);
}
