import { rand } from './core';

export function cat() {
  return rand([
    'Japanese Bobtail',
    'Savannah',
    'LaPerm',
    'Siberian',
    'Ocicat',
    'Birman',
    'Devon Rex',
    'Minskin',
    'Serengeti',
    'Bombay',
    'Himalayan',
    'American Curl',
    'Thai',
    'Balinese',
    'Singapura',
    'American Shorthair',
    'Ojos Azules',
    'Burmese',
    'Kurilian Bobtail',
    'American Bobtail',
    'Maine Coon',
    'Somali',
    'Abyssinian',
    'Nebelung',
    'Norwegian Forest Cat',
    'Sphynx',
    'Toyger',
    'American Wirehair',
    'Tonkinese',
    'Highlander',
    'Munchkin',
    'Persian',
    'Havana',
    'Exotic Shorthair',
    'Donskoy',
    'Peterbald',
    'Scottish Fold',
    'Snowshoe',
    'Pixiebob',
    'Turkish Angora',
    'Egyptian Mau',
    'Oriental',
    'Chausie',
    'Ragdoll',
    'Chartreux',
    'Manx',
  ]);
}
