import { rand } from './core';

export function cetacean() {
  return rand([
    'Clymene Dolphin',
    'Bottlenose Dolphin',
    'Costero',
    'Chilean Dolphin',
    'Heaviside’s Dolphin',
    'Pantropical Spotted Dolphin',
    'Sperm Whale',
    'Burrunan Dolphin',
    'Bryde’s whale',
    'Atlantic White-Sided Dolphin',
    'Northern Rightwhale Dolphin',
    'Killer Whale (Orca)',
    'False Killer Whale',
    'Ganges River Dolphin',
    'Pacific White-Sided Dolphin',
    'Blue Whale',
    'Southern Bottlenose Whale',
    'Peale’s Dolphin',
    'Amazon River Dolphin',
    'Omura’s whale',
    "Longman's Beaked Whale",
    'Irrawaddy Dolphin',
    'Long-Beaked Common Dolphin',
    'Guiana Dolphin',
    'Chinese River Dolphin',
    'Dusky Dolphin',
    'Commerson’s Dolphin',
    'Indo-Pacific Hump-backed Dolphin',
    'Atlantic Humpbacked Dolphin',
    'Tucuxi',
    'Fin Whale',
    "Arnoux's Beaked Whale",
    'Long-finned Pilot Whale',
    'Hourglass Dolphin',
    'Australian humpback Dolphin',
    'Sei Whale',
    'Melon-headed Whale',
    'Atlantic Spotted Dolphin',
    'Striped Dolphin',
    'La Plata Dolphin',
    'Indo-Pacific Bottlenose Dolphin',
    'Humpback whale',
    'Short-Beaked Common Dolphin',
    'Risso’s Dolphin',
    'White-Beaked Dolphin',
    'Rough-Toothed Dolphin',
  ]);
}
