import { rand } from './core';

export function cityName() {
  return rand([
    'Kent',
    'Waterloo',
    'Oakland Park',
    'Rowlett',
    'North Richland Hills',
    'Skokie',
    'Davis',
    'Overland Park',
    'Rialto',
    'Tracy',
    'South Whittier',
    'Parker',
    'Denver',
    'Lancaster',
    'Corpus Christi',
    'McAllen',
    'Boulder',
    'Merced',
    'Paradise',
    'Rochester',
    'Danville',
    'La Mirada',
    'Indianapolis',
    'El Dorado Hills',
    'Bothell',
    'Taylorsville',
    'Enterprise',
    'Highland',
    'Moore',
    'Bradenton',
    'Largo',
    'Upland',
    'Utica',
    'Aloha',
    'Tempe',
    'Kokomo',
    'Montebello',
    'Coon Rapids',
    'Carson',
    'Union City',
    'Aliso Viejo',
    'Plainfield',
    'Boston',
    'El Centro',
    'Columbia',
    'West Palm Beach',
    'Tyler',
    'Lakewood',
    'Carolina',
    'Lehigh Acres',
    'Glendale',
    'Middletown',
    'Hillsboro',
    'Victorville',
    'Country Club',
    'Summerville',
    'Azusa',
    'Covina',
    'Pawtucket',
    'Findlay',
    'Palm Beach Gardens',
    'Arlington',
    'Eau Claire',
    'Buffalo',
    'Burleson',
    'Springfield',
    'Baton Rouge',
    'Surprise',
    'Meriden',
    'Mesa',
    'Lake Charles',
    'Fond du Lac',
    'San Buenaventura (Ventura)',
    'Westland',
    'Hartford',
    'Round Rock',
    'Chattanooga',
    'Pleasanton',
    'Nampa',
    'York',
    'Keller',
    'Murfreesboro',
    'Jurupa Valley',
    'Spokane',
    'Sanford',
    'Rio Rancho',
    'West Valley City',
    'Decatur',
    'Pensacola',
    'Pembroke Pines',
    'Santa Clarita',
    'Palm Coast',
  ]);
}
