import { rand } from './core';

export function cow() {
  return rand([
    'Hartón del Valle',
    'Pedit',
    'German Black Pied cattle',
    'Parda Alpina',
    'Dajal',
    'Raya',
    'Adamawa',
    'Blaarkop',
    'Doayo cattle',
    'Aulie-Ata',
    'North Bengal Grey',
    'Nguni',
    'Canaria',
    'Siri',
    'Breed',
    'Hallikar4',
    'Simmental',
    'Pie Rouge des Plaines',
    'Khillari cattle',
    'Romagnola',
    'Original Simmental',
    'Dwarf Lulu',
    'Square Meater',
    'Galician Blond',
    'Kenkatha cattle',
    'Estonian Red cattle',
    'Blanca Cacereña',
    'Glan cattle',
    'Friesian Red and White',
    'Volinian Beef',
    'Ponwar',
    'Kankrej',
    'Bachaur cattle',
    'Aleutian wild cattle',
    'Abigar',
    'Dutch Belted',
    'Afar',
    'Belmont Red',
    'Romanian Steppe Gray',
    'Fjäll',
    'Tuli',
    'Bakosi cattle',
    'British Friesian',
    'Cholistani',
    'Hereford',
    'Kurgan cattle',
    'Canadian Speckle Park',
    'Vorderwald',
    'American Beef Friesian',
    'Braford',
    'Lincoln Red',
    'Arsi',
    'Mirkadim',
    'Black Hereford',
    'Uedit',
    'Malnad Gidda',
    'Pinzgauer',
    'Costeño con Cuernos',
    'Thai Milking Zebu',
    'Serbian Steppe',
    'Senepol',
    'Ongole',
    'Limia cattle',
    'Latvian Brown',
    'Ennstaler Bergscheck',
    'Red Fulani',
    'Hybridmaster',
    'Thai Fighting Bull',
    'Randall',
    'Doela',
    'Black Baldy',
    'Milking Shorthorn',
    'Azores',
    'Kostroma cattle',
    'Estonian Native',
    'Tulim',
    'Devon',
    'Shorthorn',
    'Belgian Red Pied',
    'Fleckvieh',
    'Yanbian',
    'Dhanni',
    'Red Poll',
    'Gelbvieh',
    'Brahmousin',
    'Wedit',
    'Coloursided White Back',
    'Blue Grey',
  ]);
}
