import { rand } from './core';

export function phrase() {
  return rand([
    'Try to program the GB interface, maybe it will copy the wireless hard drive!',
    'Try to bypass the GB panel, maybe it will synthesize the back-end transmitter!',
    'If we program the protocol, we can get to the SDD application through the virtual RAM pixel!',
    'Use the open-source THX application, then you can quantify the solid state transmitter!',
    "You can't transmit the firewall without copying the 1080p SDD interface!",
    "I'll compress the open-source SAS bandwidth, that should array the FTP port!",
    "programming the alarm won't do anything, we need to hack the solid state ADP transmitter!",
    "calculating the interface won't do anything, we need to bypass the mobile IB panel!",
    'Try to calculate the GB transmitter, maybe it will quantify the online pixel!',
    'If we calculate the circuit, we can get to the HDD driver through the optical XML panel!',
    "navigating the program won't do anything, we need to calculate the cross-platform SMS capacitor!",
    'Try to calculate the JBOD firewall, maybe it will override the redundant port!',
    'If we quantify the alarm, we can get to the FTP pixel through the online SSL interface!',
    "You can't override the capacitor without indexing the bluetooth PNG pixel!",
    "quantifying the microchip won't do anything, we need to index the online SQL hard drive!",
    "connecting the port won't do anything, we need to program the haptic RSS pixel!",
    'We need to back up the 1080p JBOD bandwidth!',
    'If we index the card, we can get to the SMS hard drive through the bluetooth AGP bus!',
    "I'll compress the optical SDD hard drive, that should interface the XSS bandwidth!",
    "You can't copy the feed without compressing the primary JBOD circuit!",
    'If we back up the application, we can get to the TCP bus through the auxiliary FTP hard drive!',
    'Try to override the RSS port, maybe it will quantify the haptic port!',
    'We need to calculate the bluetooth JBOD bus!',
    "bypassing the bus won't do anything, we need to program the wireless SDD driver!",
    'Try to parse the PCI capacitor, maybe it will quantify the bluetooth interface!',
    "copying the monitor won't do anything, we need to synthesize the back-end ADP application!",
    'Try to index the PNG card, maybe it will transmit the neural system!',
    'Try to bypass the SCSI sensor, maybe it will generate the 1080p card!',
    'We need to calculate the open-source SDD driver!',
    'If we reboot the port, we can get to the RSS application through the 1080p SQL microchip!',
    'Use the cross-platform AI system, then you can connect the digital card!',
    'We need to navigate the virtual SSL transmitter!',
    'The JSON hard drive is down, bypass the redundant firewall so we can copy the FTP port!',
    'We need to navigate the haptic JBOD system!',
    'We need to generate the virtual USB pixel!',
    "I'll override the digital ADP alarm, that should microchip the USB firewall!",
    'We need to bypass the redundant RAM pixel!',
    "I'll compress the cross-platform EXE card, that should circuit the AGP sensor!",
    'The AGP protocol is down, compress the open-source card so we can override the XML program!',
    "I'll reboot the bluetooth GB capacitor, that should card the HDD panel!",
    "I'll connect the neural IB matrix, that should array the CSS card!",
    'The EXE matrix is down, transmit the wireless matrix so we can index the RAM pixel!',
    'The THX monitor is down, reboot the auxiliary array so we can parse the XML microchip!',
    'Try to override the HDD firewall, maybe it will generate the open-source panel!',
    'We need to index the digital JBOD bus!',
    'Use the multi-byte THX firewall, then you can back up the digital system!',
    'Use the 1080p IB feed, then you can reboot the haptic feed!',
    'Try to bypass the SAS card, maybe it will transmit the solid state system!',
    'Try to quantify the TCP array, maybe it will index the virtual transmitter!',
    "I'll override the cross-platform PCI port, that should driver the FTP card!",
    'If we override the bandwidth, we can get to the SMTP capacitor through the cross-platform RSS alarm!',
    'Use the redundant AGP transmitter, then you can generate the 1080p circuit!',
    'Use the auxiliary EXE monitor, then you can hack the haptic port!',
    'Try to synthesize the SCSI card, maybe it will back up the 1080p circuit!',
    'We need to transmit the auxiliary GB sensor!',
    'Use the mobile GB transmitter, then you can quantify the wireless system!',
    'Try to quantify the SQL application, maybe it will bypass the primary pixel!',
    "You can't override the protocol without programming the mobile RAM card!",
    'The JBOD port is down, program the wireless array so we can input the PCI program!',
    'Use the auxiliary JSON card, then you can copy the optical matrix!',
    'We need to calculate the wireless TCP circuit!',
    'Use the back-end AI firewall, then you can parse the optical program!',
    "navigating the hard drive won't do anything, we need to synthesize the auxiliary USB circuit!",
    "I'll quantify the redundant TCP bus, that should hard drive the ADP bandwidth!",
    'If we back up the sensor, we can get to the JBOD matrix through the optical EXE alarm!',
    'Try to generate the TCP bus, maybe it will override the neural bandwidth!',
    'The ADP protocol is down, parse the 1080p card so we can reboot the ADP application!',
    "calculating the driver won't do anything, we need to generate the optical SMTP feed!",
    "I'll calculate the 1080p XML transmitter, that should alarm the RSS firewall!",
    "You can't connect the interface without programming the virtual PNG protocol!",
    'Use the cross-platform THX array, then you can parse the primary capacitor!',
    "generating the sensor won't do anything, we need to hack the solid state AI bus!",
    'Try to calculate the JBOD program, maybe it will synthesize the mobile system!',
    'We need to program the back-end PNG pixel!',
    "I'll program the virtual XML microchip, that should transmitter the SDD protocol!",
    'If we hack the firewall, we can get to the USB application through the bluetooth SDD system!',
    'Use the auxiliary SDD system, then you can input the redundant hard drive!',
    'The GB port is down, quantify the mobile circuit so we can hack the SMTP system!',
    "You can't quantify the driver without transmitting the multi-byte SQL microchip!",
    'Try to parse the SMTP array, maybe it will generate the multi-byte port!',
    "copying the system won't do anything, we need to calculate the virtual SSL circuit!",
    'Use the bluetooth TCP capacitor, then you can reboot the open-source hard drive!',
    'If we navigate the card, we can get to the ADP array through the open-source IB feed!',
    'Try to input the HTTP feed, maybe it will reboot the mobile capacitor!',
    'If we input the driver, we can get to the RAM monitor through the 1080p GB bus!',
    "I'll calculate the wireless ADP port, that should bandwidth the SSL microchip!",
    'Use the haptic XSS driver, then you can connect the wireless program!',
    "quantifying the circuit won't do anything, we need to parse the back-end FTP interface!",
    "I'll reboot the online COM interface, that should system the THX protocol!",
    'Try to transmit the HTTP card, maybe it will override the multi-byte hard drive!',
    "I'll program the back-end THX matrix, that should interface the HDD panel!",
    "I'll generate the virtual SQL protocol, that should bus the AI hard drive!",
    'We need to calculate the mobile AGP panel!',
    "I'll compress the back-end PCI circuit, that should monitor the PNG driver!",
    'We need to quantify the primary TCP matrix!',
    "I'll synthesize the primary AI capacitor, that should array the JBOD sensor!",
    "You can't hack the card without indexing the primary XSS capacitor!",
    'The TCP feed is down, compress the cross-platform alarm so we can synthesize the XSS array!',
    'The JSON interface is down, hack the haptic transmitter so we can bypass the XML system!',
    'Use the online SDD protocol, then you can parse the open-source bandwidth!',
  ]);
}
