import { rand } from './core';

export function rabbit() {
  return rand([
    'Satin',
    'Giant Angora',
    'Tan',
    'Havana',
    'Harlequin',
    'Rhinelander',
    'Cinnamon',
    'American',
    'Florida White',
    'Checkered Giant',
    'English Lop',
    'Polish',
    'English Angora',
    'Belgian Hare',
    'Standard Chinchilla',
    'Giant Chinchilla',
    'English Spot',
    'Dutch',
    'American Chinchilla',
    'Satin Angora',
    'Argente Brun',
    'American Fuzzy Lop',
    'Blanc de Hotot',
    'Holland Lop',
    'Silver',
    'Flemish Giant',
    'Lilac',
    'Rex',
    'Netherland Dwarf',
    'Mini Satin',
    'Silver Marten',
    'French Lop',
    'Thrianta',
    'Jersey Wooly',
    'Lionhead',
    'Mini Lop',
    'Mini Rex',
    'Britannia Petite',
    'American Sable',
    'Himalayan',
    'Crème D’Argent',
  ]);
}
