import { rand } from './core';

export function snake() {
  return rand([
    'Bluntnose viper',
    'Yunnan keelback',
    'Eastern hognose snake',
    'Southwestern black spitting cobra',
    'Machete savane',
    'Angolan python',
    "Hutton's tree viper",
    'Eastern tiger snake',
    'Central ranges taipan',
    "Schultze's pitviper",
    'Mexican west coast rattlesnake',
    'Indigo snake',
    'Dog-toothed cat snake',
    'Bismarck ringed python',
    'Boomslang',
    'Mangshan pitviper',
    'Whip snake',
    'Mountain adder',
    'Tan racer',
    'Twin-spotted rat snake',
    'Emerald tree boa',
    'Sumatran short-tailed python',
    'Hairy bush viper',
    'Mozambique spitting cobra',
    'Coral snake',
    'Cape coral snake',
    'Coachwhip snake',
    'Puff adder',
    'Viper',
    'West Indian racer',
    'Mandarin rat snake',
    'Wolf snake',
    'Mexican parrot snake',
    'Midget faded rattlesnake',
    'Orange-collared keelback',
    'Mangrove pit viper',
    'River jack',
    'Rhombic night adder',
    'Common tiger snake',
    'Eastern lyre snake',
    'Blue krait',
    'Mexican green rattlesnake',
    'Fan-Si-Pan horned pitviper',
    'Indian python',
    'Brown spotted pitviper[4]',
    "Perrotet's shieldtail snake",
    "Cantor's pitviper",
    'Python',
    'Fishing snake',
    'Baja California lyresnake',
    "Stejneger's bamboo pitviper",
    'Western green mamba',
    'Common garter snake',
    "Collett's snake",
    'Zebra snake',
    'Uracoan rattlesnake',
    'Bird snake',
    'Caspian cobra',
    'Horseshoe pitviper',
    'Mollucan python',
    'Congo water cobra',
    'Tiger snake',
    'Congo snake',
    'Green snake',
    'Lance-headed rattlesnake',
    "Brongersma's pitviper",
    'Mangrove snake',
    'Stiletto snake',
    'Lora',
    'Leaf viper',
    'Northern white-lipped python',
    'Egg-eater',
    'Southern Pacific rattlesnake',
    'Harlequin coral snake',
    'Indian cobra',
    'Black-headed snake',
    'Vine snake',
    'Temple pit viper',
    'Pine snake',
    'Speckled kingsnake',
    'Black-necked spitting cobra',
    'Water adder',
    'Ball python',
    'Sand adder',
    'Southern black racer',
    'Asian cobra',
    'Flat-nosed pitviper',
    'Ground snake',
    'Great Lakes bush viper',
    'Large shield snake',
  ]);
}
