import { rand } from './core';

export function userCard() {
  return rand([
    {
      name: 'Gordon Kuphal',
      username: 'Charlene27',
      email: 'Tobin.Wuckert@gmail.com',
      address: {
        street: 'Fritsch Common',
        suite: 'Suite 890',
        city: 'East Dolores',
        zipcode: '89523',
        geo: { lat: '46.5537', lng: '-118.4174' },
      },
      phone: '1-443-483-2093',
      website: 'jalon.org',
      company: {
        name: 'Corwin - Reynolds',
        catchPhrase: 'Expanded tertiary interface',
        bs: 'expedite leading-edge niches',
      },
    },
    {
      name: 'Mr. Ian Gleason',
      username: 'Fausto_Torp',
      email: 'Chaya_Stroman54@gmail.com',
      address: {
        street: 'Perry Parkways',
        suite: 'Suite 550',
        city: 'Kirkland',
        zipcode: '71522',
        geo: { lat: '-49.7023', lng: '-28.6275' },
      },
      phone: '1-757-643-7427 x5990',
      website: 'skye.name',
      company: {
        name: 'Feest, Veum and Roberts',
        catchPhrase: 'Object-based tertiary workforce',
        bs: 'integrate cross-platform users',
      },
    },
    {
      name: 'Corey Sauer',
      username: 'Cortez68',
      email: 'Marilie95@gmail.com',
      address: {
        street: 'Rosendo Cliff',
        suite: 'Apt. 465',
        city: 'Lake Lila',
        zipcode: '27972',
        geo: { lat: '78.1654', lng: '130.6152' },
      },
      phone: '959-834-8028 x602',
      website: 'cydney.info',
      company: {
        name: 'Schamberger Group',
        catchPhrase: 'Integrated secondary leverage',
        bs: 'productize intuitive eyeballs',
      },
    },
    {
      name: 'Lucia Rodriguez',
      username: 'Tyrese.Glover38',
      email: 'Madyson_Beer27@hotmail.com',
      address: {
        street: 'Arthur Place',
        suite: 'Apt. 241',
        city: 'North Magnusberg',
        zipcode: '71973-1407',
        geo: { lat: '-80.9425', lng: '44.3110' },
      },
      phone: '858.960.4268',
      website: 'veronica.biz',
      company: {
        name: 'Leuschke - Koelpin',
        catchPhrase: 'Open-architected asynchronous encryption',
        bs: 'e-enable robust initiatives',
      },
    },
    {
      name: 'Dennis Bailey',
      username: 'Adrianna.Cronin',
      email: 'Gwen.Oberbrunner1@gmail.com',
      address: {
        street: 'Sydnie Forge',
        suite: 'Apt. 645',
        city: 'West Kendratown',
        zipcode: '34901-5017',
        geo: { lat: '53.0976', lng: '-36.3279' },
      },
      phone: '834.566.2496 x149',
      website: 'kip.net',
      company: {
        name: 'Sporer, Heathcote and Stiedemann',
        catchPhrase: 'Compatible demand-driven concept',
        bs: 'utilize e-business niches',
      },
    },
    {
      name: 'Joel Dietrich',
      username: 'Scottie_Lockman',
      email: 'Adeline6@gmail.com',
      address: {
        street: 'Crona Springs',
        suite: 'Apt. 996',
        city: 'Port Eladio',
        zipcode: '59701',
        geo: { lat: '28.3780', lng: '-97.4693' },
      },
      phone: '989.737.9797',
      website: 'denis.com',
      company: {
        name: 'Halvorson, Goyette and Greenfelder',
        catchPhrase: 'Reduced modular forecast',
        bs: 'synergize vertical web-readiness',
      },
    },
    {
      name: 'Shaun Hoppe',
      username: 'Hans.Monahan',
      email: 'Onie.Fisher15@hotmail.com',
      address: {
        street: 'Kemmer Springs',
        suite: 'Suite 457',
        city: 'Ernastad',
        zipcode: '48408-1910',
        geo: { lat: '-76.8371', lng: '-60.7557' },
      },
      phone: '653.504.5780',
      website: 'olen.org',
      company: {
        name: 'Lind - Fritsch',
        catchPhrase: 'Stand-alone value-added paradigm',
        bs: 'evolve collaborative synergies',
      },
    },
    {
      name: 'Percy Haag',
      username: 'Elisha95',
      email: 'Hal.Greenfelder1@hotmail.com',
      address: {
        street: 'Garland Rapids',
        suite: 'Suite 378',
        city: 'Hesselmouth',
        zipcode: '61502-5786',
        geo: { lat: '-80.8809', lng: '82.5266' },
      },
      phone: '429.900.2383 x11877',
      website: 'elyssa.name',
      company: {
        name: 'Hegmann and Sons',
        catchPhrase: 'Function-based dedicated knowledge base',
        bs: 'maximize seamless metrics',
      },
    },
    {
      name: 'Mrs. Lela Hills',
      username: 'Juanita_Emard21',
      email: 'Gordon.Hickle@gmail.com',
      address: {
        street: 'Octavia Via',
        suite: 'Apt. 601',
        city: 'North Torranceport',
        zipcode: '17377',
        geo: { lat: '-0.2500', lng: '40.0645' },
      },
      phone: '(534) 337-5054 x5430',
      website: 'roscoe.info',
      company: {
        name: 'Wiegand and Sons',
        catchPhrase: 'Focused holistic system engine',
        bs: 'exploit integrated web services',
      },
    },
    {
      name: 'Andrew Nolan',
      username: 'Quinton.Howe36',
      email: 'Elena.Kemmer@hotmail.com',
      address: {
        street: 'Cormier Knoll',
        suite: 'Suite 615',
        city: 'New Tessie',
        zipcode: '48255-3629',
        geo: { lat: '64.3969', lng: '-134.4582' },
      },
      phone: '1-965-879-9171 x719',
      website: 'noel.info',
      company: {
        name: 'Simonis - Davis',
        catchPhrase: 'Enterprise-wide bottom-line paradigm',
        bs: 'evolve mission-critical metrics',
      },
    },
    {
      name: 'Carolyn Schneider',
      username: 'Zelma_Wolff30',
      email: 'Audrey.Nienow20@yahoo.com',
      address: {
        street: 'Osinski Row',
        suite: 'Suite 433',
        city: 'Lake Melvinatown',
        zipcode: '46331-2385',
        geo: { lat: '-89.9290', lng: '-18.4583' },
      },
      phone: '201.906.6395 x22597',
      website: 'jaydon.info',
      company: {
        name: 'Reichert Inc',
        catchPhrase: 'Configurable next generation service-desk',
        bs: 'deploy cross-platform e-services',
      },
    },
    {
      name: 'Joyce Glover',
      username: 'Sim.Bashirian',
      email: 'Julianne_Marvin@gmail.com',
      address: {
        street: 'Lockman Oval',
        suite: 'Apt. 889',
        city: 'Owensboro',
        zipcode: '95310',
        geo: { lat: '-80.8268', lng: '151.5141' },
      },
      phone: '(795) 873-6029 x4543',
      website: 'eulalia.biz',
      company: {
        name: 'Okuneva, Bayer and Dickens',
        catchPhrase: 'Seamless high-level leverage',
        bs: 'drive user-centric infomediaries',
      },
    },
    {
      name: 'Victor Bednar',
      username: 'Oral.Ratke',
      email: 'Breanne.Hessel@gmail.com',
      address: {
        street: 'Cruickshank Loop',
        suite: 'Apt. 554',
        city: 'Troy',
        zipcode: '96303',
        geo: { lat: '44.0767', lng: '-136.9362' },
      },
      phone: '(735) 747-0273 x226',
      website: 'lempi.name',
      company: {
        name: 'Keebler - Jacobi',
        catchPhrase: 'Horizontal zero administration protocol',
        bs: 'scale dynamic synergies',
      },
    },
    {
      name: 'Ronnie Lowe',
      username: 'Mack_OKeefe',
      email: 'Jake_Turner@hotmail.com',
      address: {
        street: 'Donnelly Ports',
        suite: 'Suite 967',
        city: 'Irmatown',
        zipcode: '90752-6928',
        geo: { lat: '-20.1054', lng: '74.7606' },
      },
      phone: '221.444.9027 x554',
      website: 'reba.info',
      company: {
        name: 'Haag, Considine and Botsford',
        catchPhrase: 'Reverse-engineered coherent concept',
        bs: 'brand frictionless blockchains',
      },
    },
    {
      name: 'Jean Haag Jr.',
      username: 'Claude33',
      email: 'Oren.Jakubowski48@gmail.com',
      address: {
        street: 'Cynthia Port',
        suite: 'Suite 770',
        city: 'Houston',
        zipcode: '01328-5970',
        geo: { lat: '-67.9691', lng: '-160.1705' },
      },
      phone: '(255) 387-0318 x2868',
      website: 'kiara.org',
      company: {
        name: 'Stokes - Koepp',
        catchPhrase: 'Advanced secondary complexity',
        bs: 'e-enable impactful vortals',
      },
    },
    {
      name: 'Mrs. Tyler Huel',
      username: 'Josefina7',
      email: 'Irma3@yahoo.com',
      address: {
        street: 'Kris Parkway',
        suite: 'Suite 025',
        city: 'Vandervortborough',
        zipcode: '09524-5359',
        geo: { lat: '-88.2134', lng: '96.2084' },
      },
      phone: '714.387.0012 x52043',
      website: 'corene.com',
      company: {
        name: 'Quitzon LLC',
        catchPhrase: 'Synergistic context-sensitive hub',
        bs: 'generate viral mindshare',
      },
    },
    {
      name: 'Jimmy Hills',
      username: 'Abdul_Koepp',
      email: 'Einar_Jones@gmail.com',
      address: {
        street: 'Gordon Pines',
        suite: 'Apt. 417',
        city: 'East Connorshire',
        zipcode: '60164-9200',
        geo: { lat: '50.5624', lng: '91.5211' },
      },
      phone: '(230) 651-7339',
      website: 'andreanne.net',
      company: {
        name: 'Thompson - Mueller',
        catchPhrase: 'Vision-oriented leading edge matrices',
        bs: 'reinvent next-generation eyeballs',
      },
    },
    {
      name: 'Carole Murazik',
      username: 'Mathilde.Feest',
      email: 'Buddy77@hotmail.com',
      address: {
        street: 'Deckow Manors',
        suite: 'Suite 271',
        city: 'Lake Perry',
        zipcode: '95997',
        geo: { lat: '-57.3179', lng: '153.2830' },
      },
      phone: '(980) 245-2889 x49550',
      website: 'destini.org',
      company: {
        name: 'Frami Inc',
        catchPhrase: 'Implemented real-time customer loyalty',
        bs: 'optimize killer e-tailers',
      },
    },
    {
      name: 'Wilma Huels',
      username: 'Adolphus21',
      email: 'Khalid.Carroll14@gmail.com',
      address: {
        street: 'Rempel Streets',
        suite: 'Apt. 535',
        city: 'Jarodshire',
        zipcode: '37485-7770',
        geo: { lat: '-39.6923', lng: '-33.4824' },
      },
      phone: '958-468-5364',
      website: 'cody.info',
      company: {
        name: 'Bogisich - Gislason',
        catchPhrase: 'Enhanced value-added customer loyalty',
        bs: 'unleash end-to-end paradigms',
      },
    },
    {
      name: 'Dave Reinger',
      username: 'Cleve26',
      email: 'Laverne17@yahoo.com',
      address: {
        street: 'Heathcote Ports',
        suite: 'Suite 555',
        city: 'East Jannie',
        zipcode: '33179',
        geo: { lat: '-66.2621', lng: '-169.0325' },
      },
      phone: '1-888-882-6585 x60946',
      website: 'keyon.name',
      company: {
        name: 'Kuhlman - Schamberger',
        catchPhrase: 'Devolved maximized extranet',
        bs: 'embrace 24/7 eyeballs',
      },
    },
    {
      name: 'Eugene Gaylord',
      username: 'Aurelie_Sipes18',
      email: 'Maia.Maggio84@hotmail.com',
      address: {
        street: 'Lang Port',
        suite: 'Suite 117',
        city: 'East Mayfort',
        zipcode: '78484',
        geo: { lat: '26.3463', lng: '-17.7341' },
      },
      phone: '578.222.4582',
      website: 'theo.net',
      company: {
        name: 'Osinski - Breitenberg',
        catchPhrase: 'Down-sized eco-centric firmware',
        bs: 'strategize revolutionary communities',
      },
    },
    {
      name: 'Felix Corkery',
      username: 'Reginald_Halvorson',
      email: 'Bernie.Koss97@yahoo.com',
      address: {
        street: 'Delilah Route',
        suite: 'Apt. 897',
        city: 'New Dan',
        zipcode: '91998-5352',
        geo: { lat: '-21.3061', lng: '-3.4377' },
      },
      phone: '(661) 669-8820 x78218',
      website: 'elna.info',
      company: {
        name: 'Witting and Sons',
        catchPhrase: 'Versatile high-level alliance',
        bs: 'deliver robust eyeballs',
      },
    },
    {
      name: 'Guadalupe Bergstrom',
      username: 'Adaline_Crist76',
      email: 'Berta.Lind@yahoo.com',
      address: {
        street: 'Gerlach Lodge',
        suite: 'Suite 261',
        city: 'New Hazel',
        zipcode: '82621',
        geo: { lat: '44.2598', lng: '101.7221' },
      },
      phone: '334-844-7205',
      website: 'vinnie.biz',
      company: {
        name: 'Hickle LLC',
        catchPhrase: 'Expanded multi-state database',
        bs: 'syndicate killer communities',
      },
    },
    {
      name: 'Fernando Kirlin V',
      username: 'Johathan56',
      email: 'Angela30@yahoo.com',
      address: {
        street: 'Heidenreich Walks',
        suite: 'Apt. 191',
        city: 'Port Bill',
        zipcode: '47781-6306',
        geo: { lat: '40.7860', lng: '-57.8056' },
      },
      phone: '1-651-794-0830 x637',
      website: 'helga.info',
      company: {
        name: 'Barrows LLC',
        catchPhrase: 'Synchronised composite pricing structure',
        bs: 'repurpose B2B eyeballs',
      },
    },
    {
      name: 'Beth Hirthe',
      username: 'Nasir_Jacobs',
      email: 'Johan_Mitchell13@yahoo.com',
      address: {
        street: 'Hermiston Squares',
        suite: 'Apt. 719',
        city: 'Vacaville',
        zipcode: '05878',
        geo: { lat: '18.2610', lng: '-172.9520' },
      },
      phone: '(718) 243-6086 x48622',
      website: 'moses.com',
      company: {
        name: 'Dooley - Dickens',
        catchPhrase: 'Right-sized mission-critical leverage',
        bs: 'utilize sticky functionalities',
      },
    },
    {
      name: 'Raul Klocko',
      username: 'Alia_Cole',
      email: 'Jamir.OHara8@gmail.com',
      address: {
        street: 'Erich Centers',
        suite: 'Suite 160',
        city: 'New Annalise',
        zipcode: '04588',
        geo: { lat: '-74.5125', lng: '76.4314' },
      },
      phone: '(460) 386-0472',
      website: 'torey.org',
      company: {
        name: 'Botsford, Feest and Wyman',
        catchPhrase: 'Diverse bottom-line middleware',
        bs: 'transform granular niches',
      },
    },
    {
      name: 'Dennis Becker',
      username: 'Carolyn_Schuppe49',
      email: 'Keon87@hotmail.com',
      address: {
        street: 'Adella Shores',
        suite: 'Suite 121',
        city: 'Reneefurt',
        zipcode: '81810-7762',
        geo: { lat: '-20.0669', lng: '126.0060' },
      },
      phone: '1-529-615-1359 x610',
      website: 'kaitlin.info',
      company: {
        name: 'Jast Inc',
        catchPhrase: 'Triple-buffered interactive infrastructure',
        bs: 'expedite sticky interfaces',
      },
    },
    {
      name: 'Colleen Mills',
      username: 'Kaia51',
      email: 'Alysha18@gmail.com',
      address: {
        street: 'Letitia Dale',
        suite: 'Suite 748',
        city: 'Loweborough',
        zipcode: '98318-0470',
        geo: { lat: '72.3056', lng: '-5.1628' },
      },
      phone: '473.930.3802 x533',
      website: 'gilbert.com',
      company: {
        name: 'Barrows - Volkman',
        catchPhrase: 'Total client-server core',
        bs: 'reinvent cross-platform interfaces',
      },
    },
    {
      name: 'Mrs. Owen Stoltenberg',
      username: 'Demetrius_Kutch5',
      email: 'Kay_Wilderman@yahoo.com',
      address: {
        street: 'Batz Trace',
        suite: 'Suite 391',
        city: 'Hermannfort',
        zipcode: '81577-0980',
        geo: { lat: '-85.5359', lng: '159.8214' },
      },
      phone: '367-418-8325',
      website: 'craig.info',
      company: {
        name: 'Batz and Sons',
        catchPhrase: 'Focused local architecture',
        bs: 'innovate visionary solutions',
      },
    },
    {
      name: 'Saul Stroman',
      username: 'Jazlyn_Casper',
      email: 'Reba.Kuphal@gmail.com',
      address: {
        street: 'Zieme Prairie',
        suite: 'Apt. 931',
        city: 'West Aimee',
        zipcode: '35407-7667',
        geo: { lat: '-57.4600', lng: '-164.0469' },
      },
      phone: '777-776-2013 x15403',
      website: 'abagail.biz',
      company: {
        name: 'Padberg, McGlynn and Klein',
        catchPhrase: 'Sharable executive internet solution',
        bs: 'synergize open-source channels',
      },
    },
    {
      name: 'Kelley Jast',
      username: 'Caterina_Trantow',
      email: 'Maverick29@hotmail.com',
      address: {
        street: 'Stefanie Parks',
        suite: 'Suite 283',
        city: 'New Luigifort',
        zipcode: '45954-5208',
        geo: { lat: '85.6641', lng: '41.5469' },
      },
      phone: '1-795-710-7505',
      website: 'antonio.name',
      company: {
        name: 'Ortiz - Reichert',
        catchPhrase: 'Robust executive function',
        bs: 'facilitate collaborative vortals',
      },
    },
    {
      name: 'Chris Bergstrom',
      username: 'Brad95',
      email: 'Lou4@hotmail.com',
      address: {
        street: 'Frami Burgs',
        suite: 'Suite 358',
        city: 'East Olliebury',
        zipcode: '05527-8246',
        geo: { lat: '28.9773', lng: '88.0140' },
      },
      phone: '968.722.9863 x611',
      website: 'madaline.org',
      company: {
        name: 'Donnelly, Bogan and Powlowski',
        catchPhrase: 'Enterprise-wide analyzing success',
        bs: 'disintermediate seamless metrics',
      },
    },
    {
      name: 'Fannie Osinski',
      username: 'Jared28',
      email: 'Kari.Mueller45@gmail.com',
      address: {
        street: 'Jazmyn Groves',
        suite: 'Suite 965',
        city: 'Davenport',
        zipcode: '49410',
        geo: { lat: '-60.8706', lng: '75.9784' },
      },
      phone: '997-977-1027 x541',
      website: 'vivien.com',
      company: {
        name: 'Blick, Shields and Deckow',
        catchPhrase: 'Customizable tangible intranet',
        bs: 'benchmark intuitive metrics',
      },
    },
    {
      name: 'Elsa Hettinger',
      username: 'Herman.Marks23',
      email: 'Ozella.Ledner14@gmail.com',
      address: {
        street: 'Jensen Road',
        suite: 'Suite 373',
        city: 'North Stewartborough',
        zipcode: '61488-0812',
        geo: { lat: '-12.7470', lng: '-30.7734' },
      },
      phone: '1-506-287-1060 x730',
      website: 'gideon.com',
      company: {
        name: 'Hackett, Lueilwitz and Lind',
        catchPhrase: 'Persistent disintermediate definition',
        bs: 'target magnetic mindshare',
      },
    },
    {
      name: 'Rick Zboncak',
      username: 'Friedrich3',
      email: 'Jaime.Wisozk@gmail.com',
      address: {
        street: 'Berry Locks',
        suite: 'Apt. 659',
        city: 'Hoegerstad',
        zipcode: '67619-1548',
        geo: { lat: '9.1875', lng: '150.9625' },
      },
      phone: '281.217.8468',
      website: 'titus.biz',
      company: {
        name: 'Turner, Durgan and Jacobs',
        catchPhrase: 'Diverse asynchronous function',
        bs: 'facilitate scalable technologies',
      },
    },
    {
      name: 'Luke Leuschke',
      username: 'Vivianne_Kutch83',
      email: 'Humberto.Wisozk40@yahoo.com',
      address: {
        street: 'Wisozk Islands',
        suite: 'Suite 367',
        city: 'Lake Kathryn',
        zipcode: '42578-5032',
        geo: { lat: '-44.0552', lng: '64.3160' },
      },
      phone: '(995) 588-9702 x9396',
      website: 'luella.info',
      company: {
        name: 'Douglas, Gibson and Pacocha',
        catchPhrase: 'Triple-buffered coherent workforce',
        bs: 'brand frictionless initiatives',
      },
    },
    {
      name: 'Kerry Pfeffer DDS',
      username: 'Kayley.Skiles',
      email: 'Vena.Schaden@yahoo.com',
      address: {
        street: 'Lehner Pike',
        suite: 'Apt. 893',
        city: 'Hildegardberg',
        zipcode: '41404-8544',
        geo: { lat: '-14.5343', lng: '1.5895' },
      },
      phone: '1-611-669-6328 x24448',
      website: 'quinn.info',
      company: {
        name: 'Pfeffer, Nader and Bauch',
        catchPhrase: 'Realigned fresh-thinking open system',
        bs: 'revolutionize world-class functionalities',
      },
    },
    {
      name: 'Tony McClure',
      username: 'Derick95',
      email: 'Marlon_Kunze@hotmail.com',
      address: {
        street: 'Camron Harbor',
        suite: 'Apt. 518',
        city: 'New Peterhaven',
        zipcode: '72067',
        geo: { lat: '-27.6491', lng: '138.2529' },
      },
      phone: '1-338-339-5248',
      website: 'erich.net',
      company: {
        name: 'Beatty Inc',
        catchPhrase: 'Realigned encompassing protocol',
        bs: 'e-enable collaborative e-markets',
      },
    },
    {
      name: 'Earl Shields',
      username: 'Lily69',
      email: 'Neva38@yahoo.com',
      address: {
        street: 'Freida Walks',
        suite: 'Apt. 450',
        city: 'East Rodmouth',
        zipcode: '89732-3997',
        geo: { lat: '12.3533', lng: '113.2034' },
      },
      phone: '1-731-759-1098 x22373',
      website: 'hilma.name',
      company: {
        name: 'Schmidt, Ankunding and Legros',
        catchPhrase: 'Cross-group holistic software',
        bs: 'empower revolutionary interfaces',
      },
    },
    {
      name: 'Marco Hessel',
      username: 'Hershel65',
      email: 'Genevieve_MacGyver28@hotmail.com',
      address: {
        street: 'Stehr Ville',
        suite: 'Suite 115',
        city: 'Devinborough',
        zipcode: '05129-1887',
        geo: { lat: '-70.6718', lng: '136.9898' },
      },
      phone: '678-451-2359 x22101',
      website: 'carolanne.net',
      company: {
        name: 'Leannon Group',
        catchPhrase: 'Versatile stable archive',
        bs: 'engineer virtual content',
      },
    },
    {
      name: 'Alex Abshire',
      username: 'Hershel.Dibbert12',
      email: 'Antwan38@hotmail.com',
      address: {
        street: 'Kellie Radial',
        suite: 'Apt. 956',
        city: 'North Bernadetteport',
        zipcode: '88629-5661',
        geo: { lat: '29.7184', lng: '130.4926' },
      },
      phone: '932-349-9101 x8318',
      website: 'silas.org',
      company: {
        name: 'Quigley, Hackett and Cassin',
        catchPhrase: 'Switchable content-based emulation',
        bs: 'redefine efficient markets',
      },
    },
    {
      name: 'Timothy Gutmann IV',
      username: 'Veronica36',
      email: 'Luz34@yahoo.com',
      address: {
        street: 'Leannon Junction',
        suite: 'Suite 067',
        city: 'Maggioburgh',
        zipcode: '70430',
        geo: { lat: '-84.6384', lng: '111.5854' },
      },
      phone: '1-724-649-9259 x912',
      website: 'ayana.info',
      company: {
        name: 'Bailey - Lakin',
        catchPhrase: 'Extended intangible hub',
        bs: 'transform extensible action-items',
      },
    },
    {
      name: 'Miss Candace Welch',
      username: 'Katelynn47',
      email: 'Alexane15@gmail.com',
      address: {
        street: 'Mathias Parkways',
        suite: 'Apt. 984',
        city: 'North Samaraberg',
        zipcode: '44421',
        geo: { lat: '-48.0231', lng: '-29.3576' },
      },
      phone: '(886) 524-1950',
      website: 'addie.name',
      company: {
        name: 'Treutel, Wiegand and Hills',
        catchPhrase: 'Polarised object-oriented website',
        bs: 'exploit open-source synergies',
      },
    },
    {
      name: 'Franklin Huel',
      username: 'Kennedy.Yundt',
      email: 'Crystel90@hotmail.com',
      address: {
        street: 'Howe Locks',
        suite: 'Suite 822',
        city: 'West Mauricio',
        zipcode: '45374-8662',
        geo: { lat: '-40.4944', lng: '-59.5025' },
      },
      phone: '515.817.2932 x9810',
      website: 'reta.biz',
      company: {
        name: 'Schuster LLC',
        catchPhrase: 'Managed didactic function',
        bs: 'utilize global functionalities',
      },
    },
    {
      name: 'Mae Rippin',
      username: 'Twila25',
      email: 'Consuelo_Runolfsdottir54@hotmail.com',
      address: {
        street: 'Abshire Keys',
        suite: 'Apt. 264',
        city: 'Altamonte Springs',
        zipcode: '94203-4668',
        geo: { lat: '-63.5102', lng: '-128.4333' },
      },
      phone: '326.556.5370',
      website: 'gust.com',
      company: {
        name: 'Rutherford - Lakin',
        catchPhrase: 'Centralized actuating forecast',
        bs: 'transform scalable paradigms',
      },
    },
    {
      name: 'Ryan Wisozk',
      username: 'Emerald.Jast',
      email: 'Dorian97@yahoo.com',
      address: {
        street: 'Ilene Corners',
        suite: 'Suite 936',
        city: 'East Gileschester',
        zipcode: '36238-3501',
        geo: { lat: '-83.3101', lng: '-84.2096' },
      },
      phone: '356.341.8345',
      website: 'charlotte.org',
      company: {
        name: 'Koepp, Hermann and Boehm',
        catchPhrase: 'Total context-sensitive installation',
        bs: 'iterate proactive blockchains',
      },
    },
    {
      name: 'Javier Gislason',
      username: 'Andy_Muller',
      email: 'Oswaldo_Bechtelar@yahoo.com',
      address: {
        street: 'Efren Turnpike',
        suite: 'Suite 907',
        city: 'Bergnaumstad',
        zipcode: '93151-7124',
        geo: { lat: '21.7373', lng: '134.4841' },
      },
      phone: '259.203.5038',
      website: 'hilma.org',
      company: {
        name: 'Lebsack Group',
        catchPhrase: 'Virtual methodical installation',
        bs: 'grow back-end infomediaries',
      },
    },
    {
      name: 'Miss Donnie Lowe',
      username: 'Brooklyn_Russel17',
      email: 'Elias_Stark@gmail.com',
      address: {
        street: 'Monroe Square',
        suite: 'Suite 720',
        city: 'East Michael',
        zipcode: '19169-6530',
        geo: { lat: '-26.1736', lng: '-101.9813' },
      },
      phone: '1-411-718-4396 x7670',
      website: 'tyrell.name',
      company: {
        name: 'Cronin and Sons',
        catchPhrase: 'Business-focused exuding monitoring',
        bs: 'revolutionize clicks-and-mortar infrastructures',
      },
    },
    {
      name: 'Pat Kshlerin',
      username: 'Vallie.Becker',
      email: 'Claudie75@hotmail.com',
      address: {
        street: 'Mraz Rue',
        suite: 'Apt. 214',
        city: 'West Mattiemouth',
        zipcode: '49287-9590',
        geo: { lat: '-47.6973', lng: '-8.0572' },
      },
      phone: '(877) 703-2549',
      website: 'sandy.net',
      company: {
        name: 'Funk - Muller',
        catchPhrase: 'Centralized intermediate intranet',
        bs: 'reinvent sticky architectures',
      },
    },
    {
      name: 'Joyce Kautzer',
      username: 'Kyra_Goodwin',
      email: 'Viola_Hilpert@hotmail.com',
      address: {
        street: 'Madaline Isle',
        suite: 'Apt. 038',
        city: 'North Fionafurt',
        zipcode: '41774-5879',
        geo: { lat: '81.7405', lng: '-157.3508' },
      },
      phone: '378.396.3066 x6727',
      website: 'cristina.com',
      company: {
        name: 'Huels - Gibson',
        catchPhrase: 'Realigned encompassing toolset',
        bs: 'deploy ubiquitous schemas',
      },
    },
    {
      name: 'Lonnie Kovacek',
      username: 'Kaleb.Medhurst38',
      email: 'Koby46@hotmail.com',
      address: {
        street: 'Collier Tunnel',
        suite: 'Apt. 848',
        city: 'South Abigaylechester',
        zipcode: '62867',
        geo: { lat: '-41.9026', lng: '-95.8977' },
      },
      phone: '(956) 391-5164 x055',
      website: 'coby.net',
      company: {
        name: 'Ryan Group',
        catchPhrase: 'Open-architected stable application',
        bs: 'whiteboard vertical models',
      },
    },
    {
      name: 'Paula Braun',
      username: 'Jared94',
      email: 'Jan.Hoppe@hotmail.com',
      address: {
        street: 'Borer Islands',
        suite: 'Suite 789',
        city: 'Port Fayton',
        zipcode: '39159-8021',
        geo: { lat: '-48.9057', lng: '70.4059' },
      },
      phone: '990.475.8159 x824',
      website: 'olga.org',
      company: {
        name: 'Effertz and Sons',
        catchPhrase: 'Focused leading edge hardware',
        bs: 'e-enable one-to-one experiences',
      },
    },
    {
      name: 'Caleb Stamm',
      username: 'Mya59',
      email: 'Murl19@gmail.com',
      address: {
        street: 'Rempel Flats',
        suite: 'Suite 299',
        city: 'East Myrtice',
        zipcode: '35369',
        geo: { lat: '-19.0965', lng: '-162.5285' },
      },
      phone: '1-843-939-2813 x327',
      website: 'jailyn.org',
      company: {
        name: 'Halvorson and Sons',
        catchPhrase: 'Object-based global portal',
        bs: 'grow killer functionalities',
      },
    },
    {
      name: 'Maryann Rodriguez',
      username: 'Zoila19',
      email: 'Sonya_Collins@hotmail.com',
      address: {
        street: 'Orrin Crossroad',
        suite: 'Suite 328',
        city: 'Friedrichview',
        zipcode: '73342-7974',
        geo: { lat: '-45.4514', lng: '160.1914' },
      },
      phone: '(480) 959-1921 x48079',
      website: 'polly.net',
      company: {
        name: 'Williamson, Kovacek and Gorczany',
        catchPhrase: 'Implemented real-time product',
        bs: 'whiteboard distributed communities',
      },
    },
    {
      name: 'Darren Bergstrom',
      username: 'Olen.Wisoky',
      email: 'Cyril.Reinger@hotmail.com',
      address: {
        street: 'Herman Overpass',
        suite: 'Apt. 551',
        city: 'Melodyview',
        zipcode: '95316-1935',
        geo: { lat: '-25.4390', lng: '106.0910' },
      },
      phone: '(599) 565-5047',
      website: 'lenny.net',
      company: {
        name: 'Smitham Group',
        catchPhrase: 'Focused upward-trending help-desk',
        bs: 'repurpose leading-edge synergies',
      },
    },
    {
      name: 'Mitchell Oberbrunner',
      username: 'Dillon.Swaniawski1',
      email: 'Jazmyn.Gerlach83@gmail.com',
      address: {
        street: 'Greenfelder Dale',
        suite: 'Suite 428',
        city: 'North Oscarport',
        zipcode: '14510',
        geo: { lat: '78.1869', lng: '-114.8594' },
      },
      phone: '861-621-0419',
      website: 'mekhi.com',
      company: {
        name: 'Reichert, Turner and Sawayn',
        catchPhrase: 'Sharable bifurcated solution',
        bs: 'integrate vertical blockchains',
      },
    },
    {
      name: 'Charles Crona',
      username: 'Matt31',
      email: 'Talia25@yahoo.com',
      address: {
        street: 'Ray Flats',
        suite: 'Apt. 511',
        city: 'Claudiamouth',
        zipcode: '27419-0279',
        geo: { lat: '-40.7666', lng: '66.9141' },
      },
      phone: '729.311.6048',
      website: 'ricky.info',
      company: {
        name: 'Schuster LLC',
        catchPhrase: 'Grass-roots scalable algorithm',
        bs: 'generate viral architectures',
      },
    },
    {
      name: 'Ruth Bechtelar',
      username: 'Erwin21',
      email: 'Lonzo87@gmail.com',
      address: {
        street: 'Brenda Fall',
        suite: 'Apt. 516',
        city: 'Simonisshire',
        zipcode: '12145',
        geo: { lat: '-66.4865', lng: '98.8574' },
      },
      phone: '572.906.2871',
      website: 'mertie.name',
      company: {
        name: 'Gleason LLC',
        catchPhrase: 'Proactive responsive toolset',
        bs: 'synergize distributed experiences',
      },
    },
    {
      name: 'James Lowe',
      username: 'Tara_Jacobi99',
      email: 'Kennedi.Lubowitz@yahoo.com',
      address: {
        street: 'Maximillia Bridge',
        suite: 'Suite 784',
        city: 'Bartonburgh',
        zipcode: '79348',
        geo: { lat: '27.1962', lng: '-17.8293' },
      },
      phone: '1-740-615-8827 x5491',
      website: 'bethany.info',
      company: {
        name: 'Windler - Thiel',
        catchPhrase: 'Devolved discrete matrix',
        bs: 'integrate intuitive eyeballs',
      },
    },
    {
      name: 'Leslie Schumm IV',
      username: 'Frederique.Braun14',
      email: 'Brooks_McGlynn@hotmail.com',
      address: {
        street: 'Von Plains',
        suite: 'Suite 472',
        city: 'Nikkoside',
        zipcode: '68125',
        geo: { lat: '13.5126', lng: '-17.0323' },
      },
      phone: '(375) 769-2730 x558',
      website: 'nelda.org',
      company: {
        name: 'Robel, Stark and Bogan',
        catchPhrase: 'Phased intangible process improvement',
        bs: 'reinvent revolutionary vortals',
      },
    },
    {
      name: 'Susan Predovic',
      username: 'Adah.Nader',
      email: 'Reggie_Abernathy12@hotmail.com',
      address: {
        street: 'Jakubowski Cove',
        suite: 'Suite 324',
        city: 'Boyermouth',
        zipcode: '05244-3448',
        geo: { lat: '47.1643', lng: '52.3356' },
      },
      phone: '200-835-8780',
      website: 'erin.org',
      company: {
        name: 'Pagac - Pollich',
        catchPhrase: 'Quality-focused zero defect internet solution',
        bs: 'brand next-generation e-markets',
      },
    },
    {
      name: 'Michael Moore',
      username: 'Zelma_Lindgren66',
      email: 'Maude.Koch10@gmail.com',
      address: {
        street: 'Jace Mills',
        suite: 'Suite 813',
        city: 'West Petrabury',
        zipcode: '41128',
        geo: { lat: '33.9095', lng: '33.5272' },
      },
      phone: '1-386-488-0488 x1574',
      website: 'lucas.com',
      company: {
        name: 'Grady - Auer',
        catchPhrase: 'Operative next generation superstructure',
        bs: 'seize wireless infomediaries',
      },
    },
    {
      name: 'Cheryl Little',
      username: 'Sadie_Hegmann',
      email: 'Anabel_Hegmann@hotmail.com',
      address: {
        street: 'Feeney Cliffs',
        suite: 'Suite 217',
        city: 'North Amya',
        zipcode: '08078-5221',
        geo: { lat: '85.9252', lng: '-122.6266' },
      },
      phone: '1-882-857-7303 x110',
      website: 'sonny.biz',
      company: {
        name: 'Mosciski, Beatty and McLaughlin',
        catchPhrase: 'Exclusive scalable data-warehouse',
        bs: 'disintermediate web-enabled methodologies',
      },
    },
    {
      name: 'Elias Weissnat Sr.',
      username: 'Craig.Kilback',
      email: 'Art_Durgan@yahoo.com',
      address: {
        street: 'Orval Ports',
        suite: 'Suite 583',
        city: 'Chazmouth',
        zipcode: '96124',
        geo: { lat: '8.2505', lng: '39.7339' },
      },
      phone: '983.719.9131 x18663',
      website: 'reilly.net',
      company: {
        name: 'Borer, Marvin and Shanahan',
        catchPhrase: 'Right-sized demand-driven data-warehouse',
        bs: 'incentivize e-business e-markets',
      },
    },
    {
      name: 'Wilbert Monahan',
      username: 'Muhammad62',
      email: 'Destany_Schuppe@gmail.com',
      address: {
        street: 'Herman Flats',
        suite: 'Apt. 174',
        city: 'Lubbock',
        zipcode: '54146',
        geo: { lat: '-32.3808', lng: '-28.5331' },
      },
      phone: '(733) 522-4583',
      website: 'bradford.biz',
      company: {
        name: "O'Reilly LLC",
        catchPhrase: 'Diverse executive definition',
        bs: 'drive 24/7 models',
      },
    },
    {
      name: 'Roderick Gutkowski',
      username: 'Ansley_Olson',
      email: 'Gennaro_Ruecker66@hotmail.com',
      address: {
        street: 'Kristoffer Point',
        suite: 'Apt. 145',
        city: 'Keelingmouth',
        zipcode: '35571',
        geo: { lat: '72.3060', lng: '-28.2046' },
      },
      phone: '343.422.6309 x4372',
      website: 'ronny.name',
      company: {
        name: 'Huel LLC',
        catchPhrase: 'Persevering homogeneous solution',
        bs: 'generate seamless convergence',
      },
    },
    {
      name: 'Neil Hudson',
      username: 'Elfrieda71',
      email: 'Dayana.Weissnat0@gmail.com',
      address: {
        street: 'Mueller Haven',
        suite: 'Suite 753',
        city: 'Eloyfurt',
        zipcode: '52020',
        geo: { lat: '68.6587', lng: '108.6171' },
      },
      phone: '232.831.5077 x410',
      website: 'gabrielle.info',
      company: {
        name: 'Sporer LLC',
        catchPhrase: 'Reactive needs-based firmware',
        bs: 'monetize synergistic functionalities',
      },
    },
    {
      name: 'Katrina Bosco',
      username: 'Evans40',
      email: 'Justina_Howell@yahoo.com',
      address: {
        street: 'Marian Mount',
        suite: 'Suite 817',
        city: 'Amosville',
        zipcode: '24687',
        geo: { lat: '-65.7088', lng: '-69.7743' },
      },
      phone: '(270) 604-3425 x0293',
      website: 'meagan.biz',
      company: {
        name: 'Dickens Inc',
        catchPhrase: 'Stand-alone bandwidth-monitored methodology',
        bs: 'optimize viral metrics',
      },
    },
    {
      name: 'Kimberly Predovic',
      username: 'Anahi36',
      email: 'Joany.Parisian74@hotmail.com',
      address: {
        street: 'Wyman Inlet',
        suite: 'Apt. 146',
        city: 'Greenmouth',
        zipcode: '84712-8063',
        geo: { lat: '83.7895', lng: '-68.8444' },
      },
      phone: '511.992.4776',
      website: 'marjory.biz',
      company: {
        name: 'Lueilwitz, Stehr and Lang',
        catchPhrase: 'Future-proofed leading edge leverage',
        bs: 'redefine dot-com models',
      },
    },
    {
      name: 'Wendy Lesch',
      username: 'Gerardo.Blick',
      email: 'Berry_Gaylord10@yahoo.com',
      address: {
        street: 'Viva Pass',
        suite: 'Suite 289',
        city: 'Kiehnberg',
        zipcode: '30236-6463',
        geo: { lat: '-2.7600', lng: '-45.9898' },
      },
      phone: '(497) 526-2869',
      website: 'brian.biz',
      company: {
        name: 'Reichel Group',
        catchPhrase: 'Re-contextualized context-sensitive middleware',
        bs: 'envisioneer transparent action-items',
      },
    },
    {
      name: 'Clark Cole',
      username: 'Janice13',
      email: 'Rhea_Rohan@yahoo.com',
      address: {
        street: 'Stan Light',
        suite: 'Suite 053',
        city: 'West Travon',
        zipcode: '89449',
        geo: { lat: '-23.6220', lng: '-37.4828' },
      },
      phone: '1-693-575-0747',
      website: 'ivory.org',
      company: {
        name: 'Gutkowski - Okuneva',
        catchPhrase: 'Stand-alone multi-tasking time-frame',
        bs: 'embrace scalable ROI',
      },
    },
    {
      name: 'Bert Cremin',
      username: 'Jonathan.Fadel82',
      email: 'Zachariah.Kassulke@hotmail.com',
      address: {
        street: 'Jaylon Trace',
        suite: 'Apt. 639',
        city: 'East Erika',
        zipcode: '46834',
        geo: { lat: '-88.1590', lng: '52.2607' },
      },
      phone: '(901) 711-3990 x9945',
      website: 'marshall.name',
      company: {
        name: 'Olson, Strosin and Thompson',
        catchPhrase: 'Synergized interactive neural-net',
        bs: 'enhance synergistic interfaces',
      },
    },
    {
      name: 'Jackie Donnelly III',
      username: 'Elinore.Kessler34',
      email: 'Keshaun46@yahoo.com',
      address: {
        street: 'Mohr Unions',
        suite: 'Suite 888',
        city: 'Emardmouth',
        zipcode: '78293',
        geo: { lat: '-87.7616', lng: '9.8077' },
      },
      phone: '493.969.8080',
      website: 'tillman.biz',
      company: {
        name: 'Schiller Inc',
        catchPhrase: 'Enterprise-wide static solution',
        bs: 'morph sexy partnerships',
      },
    },
    {
      name: 'Gail Turcotte',
      username: 'Elody50',
      email: 'Queenie_Feest@yahoo.com',
      address: {
        street: 'Grady Landing',
        suite: 'Suite 807',
        city: 'Norwalk',
        zipcode: '71883',
        geo: { lat: '-4.7169', lng: '-56.2332' },
      },
      phone: '619-371-7234 x635',
      website: 'eileen.org',
      company: {
        name: 'Volkman Group',
        catchPhrase: 'Stand-alone full-range parallelism',
        bs: 'matrix seamless interfaces',
      },
    },
    {
      name: 'Cecelia Towne',
      username: 'Roxanne_Schoen92',
      email: 'Aron.Reinger@hotmail.com',
      address: {
        street: 'Kirlin Field',
        suite: 'Suite 868',
        city: 'Tremblayland',
        zipcode: '65630-2998',
        geo: { lat: '6.2926', lng: '-3.3734' },
      },
      phone: '1-699-779-9496',
      website: 'alexandrine.info',
      company: {
        name: 'Tremblay Inc',
        catchPhrase: 'Networked optimizing local area network',
        bs: 'enhance proactive web services',
      },
    },
    {
      name: 'Francisco Bins',
      username: 'Joesph.Effertz12',
      email: 'Juliet_Howell36@hotmail.com',
      address: {
        street: 'Myron Mills',
        suite: 'Suite 313',
        city: 'Indianapolis',
        zipcode: '48608-6865',
        geo: { lat: '-86.4503', lng: '126.5889' },
      },
      phone: '236-720-6950 x616',
      website: 'kristian.info',
      company: {
        name: 'Bednar and Sons',
        catchPhrase: 'Sharable bifurcated productivity',
        bs: 'drive granular experiences',
      },
    },
    {
      name: 'Jorge Schoen',
      username: 'Helena25',
      email: 'Percy_Baumbach47@yahoo.com',
      address: {
        street: 'Lera Skyway',
        suite: 'Apt. 507',
        city: 'Dimitritown',
        zipcode: '46967-8477',
        geo: { lat: '-81.3647', lng: '-155.4761' },
      },
      phone: '949-627-3123',
      website: 'nash.name',
      company: {
        name: 'Reilly - Harris',
        catchPhrase: 'Secured reciprocal customer loyalty',
        bs: 'exploit global e-business',
      },
    },
    {
      name: 'Beatrice Rodriguez',
      username: 'Gillian.Balistreri',
      email: 'Delbert75@hotmail.com',
      address: {
        street: 'Fahey Fork',
        suite: 'Apt. 920',
        city: 'Port Jeramyfort',
        zipcode: '08280',
        geo: { lat: '-58.6555', lng: '-133.4539' },
      },
      phone: '1-933-702-1244',
      website: 'sedrick.info',
      company: {
        name: 'Roberts Inc',
        catchPhrase: 'Future-proofed grid-enabled array',
        bs: 'architect interactive infomediaries',
      },
    },
    {
      name: 'Carlton Ritchie',
      username: 'Leland.Becker75',
      email: 'Kaley.Weissnat@yahoo.com',
      address: {
        street: 'Stracke Lights',
        suite: 'Suite 687',
        city: 'Lake Will',
        zipcode: '01141',
        geo: { lat: '85.9360', lng: '-107.9416' },
      },
      phone: '258-879-7131 x00317',
      website: 'orpha.info',
      company: {
        name: 'Walter, Gulgowski and Goyette',
        catchPhrase: 'Down-sized system-worthy intranet',
        bs: 'scale B2B deliverables',
      },
    },
    {
      name: 'Angelo Robel',
      username: 'Janie43',
      email: 'Patrick.Wilkinson@gmail.com',
      address: {
        street: 'Brakus Parkways',
        suite: 'Apt. 640',
        city: 'East Akeem',
        zipcode: '95890-5501',
        geo: { lat: '85.2502', lng: '-128.2586' },
      },
      phone: '1-511-280-0462',
      website: 'creola.com',
      company: {
        name: 'Jast, Boyle and Murphy',
        catchPhrase: 'Horizontal national forecast',
        bs: 'integrate 24/365 content',
      },
    },
    {
      name: 'Howard Crooks',
      username: 'Trinity_Kub84',
      email: 'Lamar.Stamm@hotmail.com',
      address: {
        street: 'Coty Pike',
        suite: 'Suite 931',
        city: 'West Nelliebury',
        zipcode: '68567-9203',
        geo: { lat: '-89.4661', lng: '119.9706' },
      },
      phone: '(259) 929-2394 x5737',
      website: 'leone.info',
      company: {
        name: 'Legros, Braun and Russel',
        catchPhrase: 'User-friendly motivating policy',
        bs: 'benchmark world-class portals',
      },
    },
    {
      name: 'Dr. Terry Carroll',
      username: 'Elouise6',
      email: 'Garnett.Feest69@gmail.com',
      address: {
        street: 'Jalon Drive',
        suite: 'Suite 023',
        city: 'Parisside',
        zipcode: '59091-6602',
        geo: { lat: '39.6598', lng: '-73.8067' },
      },
      phone: '1-458-725-2848',
      website: 'clarabelle.biz',
      company: {
        name: 'Schimmel - Parisian',
        catchPhrase: 'Face to face mission-critical local area network',
        bs: 'scale seamless architectures',
      },
    },
    {
      name: 'Roderick Halvorson',
      username: 'Riley.Hessel93',
      email: 'Freddie.Nicolas38@yahoo.com',
      address: {
        street: 'Veum Mill',
        suite: 'Apt. 569',
        city: 'North Eladio',
        zipcode: '98237',
        geo: { lat: '-64.5931', lng: '-126.0565' },
      },
      phone: '(899) 807-2417 x12860',
      website: 'kurt.biz',
      company: {
        name: 'Watsica Group',
        catchPhrase: 'Reactive fresh-thinking strategy',
        bs: 'recontextualize turn-key platforms',
      },
    },
    {
      name: 'Joanna Bode',
      username: 'Zula.Wisozk37',
      email: 'Irwin.Wolff10@yahoo.com',
      address: {
        street: 'Francisca Fork',
        suite: 'Apt. 370',
        city: 'New Maci',
        zipcode: '43129-5845',
        geo: { lat: '29.2107', lng: '144.2145' },
      },
      phone: '(238) 267-1546 x56949',
      website: 'laurine.org',
      company: {
        name: 'Bins - Emard',
        catchPhrase: 'Synergistic zero tolerance archive',
        bs: 'integrate out-of-the-box technologies',
      },
    },
    {
      name: 'Brooke Anderson',
      username: 'Vicente_Leuschke',
      email: 'Stanley.Walter68@yahoo.com',
      address: {
        street: 'Gerlach Heights',
        suite: 'Suite 070',
        city: 'New Adonis',
        zipcode: '84924',
        geo: { lat: '10.6568', lng: '-36.1483' },
      },
      phone: '(212) 478-7990 x0937',
      website: 'green.biz',
      company: {
        name: 'Homenick Group',
        catchPhrase: 'Re-engineered 3rd generation algorithm',
        bs: 'e-enable impactful solutions',
      },
    },
    {
      name: 'Miss May Bayer',
      username: 'Litzy_Cartwright',
      email: 'Easter.Prosacco@yahoo.com',
      address: {
        street: 'Eileen River',
        suite: 'Apt. 768',
        city: 'New Madilyn',
        zipcode: '07406-0778',
        geo: { lat: '69.5842', lng: '-87.8875' },
      },
      phone: '957.326.2324',
      website: 'gerry.info',
      company: {
        name: 'Beer - Cole',
        catchPhrase: 'Compatible methodical alliance',
        bs: 'incentivize one-to-one paradigms',
      },
    },
    {
      name: 'Al Wilkinson',
      username: 'Rodrick_Herman',
      email: 'Einar.Reichel@hotmail.com',
      address: {
        street: 'Camille Mill',
        suite: 'Suite 719',
        city: 'Sawaynbury',
        zipcode: '17043',
        geo: { lat: '35.8847', lng: '11.8986' },
      },
      phone: '(250) 986-4838',
      website: 'vladimir.com',
      company: {
        name: 'Bartell Group',
        catchPhrase: 'Programmable 4th generation capability',
        bs: 'monetize B2B supply-chains',
      },
    },
    {
      name: 'Mr. Beatrice Thiel',
      username: 'Leila.Runte27',
      email: 'Mercedes_Denesik@yahoo.com',
      address: {
        street: 'Hayes Mountains',
        suite: 'Apt. 168',
        city: 'Mesquite',
        zipcode: '32304',
        geo: { lat: '58.4311', lng: '-64.0856' },
      },
      phone: '868-484-6320 x1861',
      website: 'muriel.info',
      company: {
        name: 'Welch and Sons',
        catchPhrase: 'Cross-group systemic core',
        bs: 'benchmark granular web-readiness',
      },
    },
    {
      name: 'Rosemarie McDermott',
      username: 'Don.Hintz',
      email: 'Garry33@hotmail.com',
      address: {
        street: 'Mitchell Shore',
        suite: 'Suite 663',
        city: 'Legrosview',
        zipcode: '45804-2632',
        geo: { lat: '-23.4893', lng: '24.3797' },
      },
      phone: '524.371.9352',
      website: 'aubree.info',
      company: {
        name: 'Nikolaus Group',
        catchPhrase: 'Customizable clear-thinking moderator',
        bs: 'target integrated methodologies',
      },
    },
    {
      name: 'Misty Reinger',
      username: 'Gilberto_Price',
      email: 'Daphnee.Wiza@hotmail.com',
      address: {
        street: 'Rafaela Inlet',
        suite: 'Apt. 392',
        city: 'Freddyberg',
        zipcode: '14402',
        geo: { lat: '13.0144', lng: '-59.0798' },
      },
      phone: '(326) 326-3671 x00528',
      website: 'noel.com',
      company: {
        name: 'Cassin, Marvin and Hauck',
        catchPhrase: 'Public-key multi-tasking capability',
        bs: 'synthesize impactful partnerships',
      },
    },
    {
      name: 'Gene Nader I',
      username: 'Sheridan.Prohaska20',
      email: 'Golden10@hotmail.com',
      address: {
        street: 'Trevor Forest',
        suite: 'Apt. 741',
        city: 'Anthonystad',
        zipcode: '00847-8365',
        geo: { lat: '-16.8436', lng: '-73.0395' },
      },
      phone: '651-379-0465',
      website: 'gerry.net',
      company: {
        name: 'Bergnaum, Bergstrom and Ebert',
        catchPhrase: 'Stand-alone actuating productivity',
        bs: 'reinvent one-to-one blockchains',
      },
    },
    {
      name: 'Mrs. Ernestine Koss',
      username: 'Collin64',
      email: 'Jedidiah.Koss41@gmail.com',
      address: {
        street: 'Lueilwitz Extension',
        suite: 'Apt. 502',
        city: 'Roobmouth',
        zipcode: '50012',
        geo: { lat: '6.1401', lng: '-49.6280' },
      },
      phone: '371.778.0714',
      website: 'rocky.info',
      company: {
        name: 'Fadel Group',
        catchPhrase: 'Multi-lateral optimal local area network',
        bs: 'cultivate cross-media users',
      },
    },
    {
      name: 'Keith Balistreri',
      username: 'Mozelle_Mills',
      email: 'Loy88@gmail.com',
      address: {
        street: 'Samanta Hill',
        suite: 'Apt. 906',
        city: 'Trujillo Alto',
        zipcode: '21509',
        geo: { lat: '-47.0727', lng: '114.5596' },
      },
      phone: '(222) 736-3397 x3026',
      website: 'dayton.net',
      company: {
        name: 'Simonis Inc',
        catchPhrase: 'Intuitive local product',
        bs: 'leverage extensible applications',
      },
    },
    {
      name: 'Wilfred Dare',
      username: 'Marlene.Hammes',
      email: 'Darrell20@hotmail.com',
      address: {
        street: 'Bergstrom Islands',
        suite: 'Apt. 446',
        city: 'Hollywood',
        zipcode: '66039-4906',
        geo: { lat: '-65.7196', lng: '89.7724' },
      },
      phone: '934-367-5703',
      website: 'chanel.com',
      company: {
        name: 'Emard Inc',
        catchPhrase: 'Business-focused actuating frame',
        bs: 'redefine bleeding-edge bandwidth',
      },
    },
    {
      name: 'Nick Batz',
      username: 'Kenyatta.Abshire77',
      email: 'Osborne.Jakubowski29@hotmail.com',
      address: {
        street: 'Delilah Brooks',
        suite: 'Apt. 151',
        city: 'New Toyfurt',
        zipcode: '16802',
        geo: { lat: '41.9222', lng: '-29.8868' },
      },
      phone: '214.286.5694 x8584',
      website: 'norris.info',
      company: {
        name: 'Pollich, Dicki and Langworth',
        catchPhrase: 'Compatible contextually-based local area network',
        bs: 'incubate real-time paradigms',
      },
    },
    {
      name: 'Omar Blanda V',
      username: 'Unique_Metz',
      email: 'Marquis_Cole84@yahoo.com',
      address: {
        street: 'Senger Pines',
        suite: 'Apt. 724',
        city: 'Albany',
        zipcode: '70202-3639',
        geo: { lat: '-31.4325', lng: '158.2084' },
      },
      phone: '(742) 499-2369 x8101',
      website: 'cathy.net',
      company: {
        name: 'Davis Group',
        catchPhrase: 'Profit-focused zero administration utilisation',
        bs: 'scale cross-media initiatives',
      },
    },
    {
      name: 'Dr. Ervin Dicki',
      username: 'Annie3',
      email: 'Tyreek.Stark@yahoo.com',
      address: {
        street: 'Dewitt Manors',
        suite: 'Apt. 439',
        city: 'Port Tatyanaburgh',
        zipcode: '29895-2048',
        geo: { lat: '-78.4970', lng: '125.0658' },
      },
      phone: '905-253-7423 x961',
      website: 'tamia.name',
      company: {
        name: 'Keeling - Fadel',
        catchPhrase: 'Innovative zero tolerance analyzer',
        bs: 'synergize cutting-edge portals',
      },
    },
    {
      name: 'Viola Langosh',
      username: 'Priscilla91',
      email: 'Sterling_Padberg@gmail.com',
      address: {
        street: 'Aaliyah Glen',
        suite: 'Apt. 679',
        city: 'Lake Jessicaland',
        zipcode: '26574',
        geo: { lat: '3.2503', lng: '108.8751' },
      },
      phone: '1-725-955-4827 x5222',
      website: 'enos.org',
      company: {
        name: 'Marquardt LLC',
        catchPhrase: 'Horizontal logistical concept',
        bs: 'seize synergistic communities',
      },
    },
    {
      name: 'Levi Turcotte',
      username: 'Terrill_Senger',
      email: 'Liam.Morissette65@yahoo.com',
      address: {
        street: 'Hauck Freeway',
        suite: 'Apt. 527',
        city: 'New Reecetown',
        zipcode: '16214',
        geo: { lat: '71.8620', lng: '7.4756' },
      },
      phone: '928-830-3062',
      website: 'nicholaus.biz',
      company: {
        name: 'Veum Inc',
        catchPhrase: 'Progressive static benchmark',
        bs: 'innovate robust e-tailers',
      },
    },
    {
      name: 'Heather Wunsch',
      username: 'Marielle.Kautzer64',
      email: 'Jamaal_Baumbach@hotmail.com',
      address: {
        street: 'Danika Mountains',
        suite: 'Suite 542',
        city: 'Lake Dagmar',
        zipcode: '94927-7687',
        geo: { lat: '49.1963', lng: '-173.8835' },
      },
      phone: '455.314.8766 x4872',
      website: 'gregoria.biz',
      company: {
        name: 'Lesch, Hettinger and Rogahn',
        catchPhrase: 'Right-sized high-level complexity',
        bs: 'deploy killer experiences',
      },
    },
  ]);
}
