import { rand } from './core';

export function vehicleModel() {
  return rand([
    'Alpine',
    'Land Cruiser',
    'Grand Cherokee',
    'A4',
    'Golf',
    'Accord',
    'Expedition',
    'Camry',
    'Jetta',
    'Taurus',
    'Camaro',
    'Prius',
    'CX-9',
    'Wrangler',
    'Civic',
    'Explorer',
    'Sentra',
    'Silverado',
    'CTS',
    'Grand Caravan',
    'Cruze',
    'PT Cruiser',
    'Spyder',
    'Model T',
    '2',
    'Colorado',
    'Corvette',
    'ATS',
    'Volt',
    'Aventador',
    'Model 3',
    'Ranchero',
    '1',
    'Focus',
    'F-150',
    'XTS',
    'A8',
    'Impala',
    'Malibu',
    'Charger',
    'Element',
    'Escalade',
    'LeBaron',
    'Fortwo',
    'Mercielago',
    'Fiesta',
    'V90',
    'Altima',
    '911',
  ]);
}
