import { rand } from './core';

export function vehicle() {
  return rand([
    'Toyota Volt',
    'Rolls Royce XC90',
    'Nissan Fiesta',
    'Mercedes Benz A4',
    'Bugatti 1',
    'Mini Explorer',
    'Nissan Spyder',
    'Kia Spyder',
    'Ford Camry',
    'Bugatti Corvette',
    'Toyota A4',
    'Toyota Challenger',
    'Smart Focus',
    'Mazda Challenger',
    'Lamborghini F-150',
    'Lamborghini Prius',
    'Hyundai Roadster',
    'Chevrolet Malibu',
    'Fiat Jetta',
    'Ford V90',
    'Mini PT Cruiser',
    'Audi Grand Caravan',
    'Ford CTS',
    'Mazda Fortwo',
    'Ferrari Corvette',
    'Dodge Corvette',
    'Hyundai 1',
    'Chevrolet Beetle',
    'Land Rover 1',
    'Mini Colorado',
    'Fiat Sentra',
    'Audi PT Cruiser',
    'Toyota F-150',
    'Jaguar Fortwo',
    'Audi Cruze',
    'Fiat Corvette',
    'Kia Model S',
    'Polestar Wrangler',
    'Honda Land Cruiser',
    'Mercedes Benz Sentra',
    'Land Rover Taurus',
    'Lamborghini Model T',
    'Rolls Royce ATS',
    'BMW Ranchero',
    'Hyundai Mustang',
    'Kia 2',
    'Jeep Mustang',
    'Jeep Explorer',
    'Dodge Model T',
    'Ferrari Durango',
    'Jaguar Grand Cherokee',
    'Jaguar Beetle',
    'Cadillac Spyder',
    'Polestar XTS',
    'Bugatti Jetta',
    'BMW Silverado',
    'Tesla CTS',
    'Jaguar Mercielago',
    'Bugatti 911',
    'Jeep Ranchero',
    'BMW Golf',
    'Lamborghini Sentra',
    'Rolls Royce Ranchero',
    'Mini Camry',
    'Bentley Prius',
    'Volkswagen Malibu',
    'Bentley XC90',
    'Chevrolet 911',
    'Mercedes Benz V90',
    'Chrysler Spyder',
    'Cadillac Camaro',
    'Nissan Explorer',
    'Polestar Challenger',
    'Honda Challenger',
    'Nissan PT Cruiser',
    'Smart Charger',
    'BMW Focus',
    'Hyundai Volt',
    'Hyundai Durango',
    'Hyundai F-150',
    'Porsche A8',
    'Audi Escalade',
    'Mazda Beetle',
    'Dodge Fiesta',
    'Ford Taurus',
    'Honda Camaro',
    'Mercedes Benz Charger',
    'Lamborghini XC90',
    'Bugatti Beetle',
    'Jaguar Focus',
    'Chrysler ATS',
    'Nissan XTS',
    'Cadillac Mercielago',
    'Mercedes Benz Aventador',
    'Land Rover Corvette',
    'Lamborghini 2',
  ]);
}
