import { rand } from './core';

export function vehicleManufacturer() {
  return rand([
    'Hyundai',
    'Volvo',
    'Smart',
    'Rolls Royce',
    'Dodge',
    'Honda',
    'Porsche',
    'Mercedes Benz',
    'Volkswagen',
    'Aston Martin',
    'Bugatti',
    'Chrysler',
    'Audi',
    'Bentley',
    'Nissan',
    'Ford',
    'Ferrari',
    'Mazda',
    'Maserati',
    'Jaguar',
    'Lamborghini',
    'Jeep',
    'Toyota',
    'Land Rover',
    'Cadillac',
    'Fiat',
    'Polestar',
    'Kia',
    'Chevrolet',
    'Tesla',
    'Mini',
  ]);
}
